### ISSUE TITLE
Error on Mac M2. Jupyter not found.

### ISSUE THREAD

**Issue by nico-canta** [CNS-OIST/STEPS_Docker#19]
When I run `docker-compose up lab` I get the following error:

````
>> docker-compose up lab

[+] Building 0.0s (0/0)                                                                                                 
[+] Running 2/0
 ✔ Container steps_docker-lab-1                                                                                                                       Created0.0s 
 ! lab The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested 0.0s 
Attaching to steps_docker-lab-1
steps_docker-lab-1  | Traceback (most recent call last):
steps_docker-lab-1  |   File "/usr/bin/jupyter", line 11, in <module>
steps_docker-lab-1  |     load_entry_point('jupyter-core==4.6.3', 'console_scripts', 'jupyter')()
steps_docker-lab-1  |   File "/usr/lib/python3/dist-packages/jupyter_core/command.py", line 247, in main
steps_docker-lab-1  |     command = _jupyter_abspath(subcommand)
steps_docker-lab-1  |   File "/usr/lib/python3/dist-packages/jupyter_core/command.py", line 133, in _jupyter_abspath
steps_docker-lab-1  |     raise Exception(
steps_docker-lab-1  | Exception: Jupyter command `jupyter-lab` not found.
steps_docker-lab-1 exited with code 1

**Comment by tristan0x** [comment]
Hello @nico-canta 
Which version of STEPS do you want to use?
Which git branch of this repository are you using? It should be `dist-steps`

**Comment by nico-canta** [comment]
Hi @tristan0x 
I was using the `master` branch.  I didn't specify the STEPS version. 
Now I am on the `dist-steps` branch, and I get a different error:
```
>> docker-compose pull

[+] Pulling 1/1
 ! lab Warning
WARNING: Some service image(s) must be built from source by running:
    docker compose build lab
1 error occurred:
	* Error response from daemon: manifest for cnsoist/steps:4.1.1 not found: manifest unknown: manifest unknown
```
```	
>> docker compose build lab

=> ERROR [lab  4/11] RUN echo 'export PATH=/opt/conda/bin:$PATH' > /etc/profile.d/conda.sh  && wget --quiet https://repo.continuum.io/miniconda/Miniconda3-py39_23.1.0-1-Linux-x86_64.sh -O ~/miniconda.sh  && /bin/bash ~/miniconda.sh -b -p /opt/conda  && rm ~/miniconda.sh  &  2.2s
------                                                                                                                                                                                                                                                                                   
 > [lab  4/11] RUN echo 'export PATH=/opt/conda/bin:$PATH' > /etc/profile.d/conda.sh  && wget --quiet https://repo.continuum.io/miniconda/Miniconda3-py39_23.1.0-1-Linux-x86_64.sh -O ~/miniconda.sh  && /bin/bash ~/miniconda.sh -b -p /opt/conda  && rm ~/miniconda.sh  && /opt/conda/bin/pip install     cython     jupyter     jupyterlab     matplotlib     nose     python-libsbml     scipy && /opt/conda/bin/conda install mpi4py && /opt/conda/bin/conda install -c conda-forge petsc:
#0 1.949 PREFIX=/opt/conda
#0 2.173 Unpacking payload ...
#0 2.175 qemu-x86_64: Could not open '/lib64/ld-linux-x86-64.so.2': No such file or directory
------
failed to solve: process "/bin/sh -c echo 'export PATH=/opt/conda/bin:$PATH' > /etc/profile.d/conda.sh  && wget --quiet https://repo.continuum.io/miniconda/Miniconda${MINICONDA_VERSION}-Linux-x86_64.sh -O ~/miniconda.sh  && /bin/bash ~/miniconda.sh -b -p /opt/conda  && rm ~/miniconda.sh  && /opt/conda/bin/pip install     cython     jupyter     jupyterlab     matplotlib     nose     python-libsbml     scipy && /opt/conda/bin/conda install mpi4py && /opt/conda/bin/conda install -c conda-forge petsc" did not complete successfully: exit code: 255
```

**Comment by tristan0x** [comment]
Hello @nico-canta 
Thank you for your feedback. I have just pushed a fix to force the emulation.
Can you please give it a try?

**Comment by nico-canta** [comment]
Thanks @tristan0x. Now it works perfectly!
